var test_questions = [

    {
        prompt: "Which could NOT be a characteristic of a prokaryotic cell?",
        qstn1: "A true nucleus",
        qstn2: "Ribosomes",
        qstn3: "DNA",
        qstn4: "A Cell'",
        answr: "A",
    },
    {
        prompt: "Add: 100+1.01+0.01+0.00001",
        qstn1: "101.01001",
        qstn2: "101.12001",
        qstn3: "101.11001",
        qstn4: "101.02001",
        answr: "D",
    },
    {
        prompt: "Which of the following cells that have both a cell wall / membrane?",
        qstn1: "Fungal & Animal Cells",
        qstn2: "Bacterial & Animal Cells",
        qstn3: "Bacterial & Fungal Cells",
        qstn4: "Fungal, Bacterial, & Animal Cells",
        answr: "C",
    },
    {
        prompt: "Which empire was dominant in the Indian subcontinent before the British?",
        qstn1: "The Nepalese Empire",
        qstn2: "The Mughal Empire",
        qstn3: "The Persian Empire",
        qstn4: "The Chinese Empire",
        answr: "B",
    },
    {
        prompt: "Which of the following is an example of primary consumers?",
        qstn1: "Algae",
        qstn2: "Deer eating grass",
        qstn3: "Fungi that gain energy from detritus",
        qstn4: "Foxes eating squirrels",
        answr: "B",
    },
    {
        prompt: "The Meiji restoration occurred in __________.",
        qstn1: "Korea",
        qstn2: "Russia",
        qstn3: "Japan",
        qstn4: "China",
        answr: "C",
    },
    {
        prompt: "The XYZ affair was important because __________.",
        qstn1: "It led to the construction of the United States Navy",
        qstn2: "It caused the United States to stop trading with Britain",
        qstn3: "It caused the United States to declare war on France",
        qstn4: "It caused the United States to declare war against Britain",
        answr: "A",
    },
    {
        prompt: "The U.S. military took possession of the Phillipines during:",
        qstn1: "World War II",
        qstn2: "World War I",
        qstn3: "Korean War",
        qstn4: "Spanish-American War",
        answr: "A",
    },
    {
        prompt: "What year was the war of 1812 fought?",
        qstn1: "1813",
        qstn2: "2043",
        qstn3: "1812",
        qstn4: "1985",
        answr: "C",
    },
    {
        prompt: "Julie scored 100,90,67,89, & 78. What was the mean of her scores?",
        qstn1: "84.8",
        qstn2: "87.1",
        qstn3: "79.9",
        qstn4: "92.4",
        answr: "A",
    },

]